name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build-ipxe
  cancel-in-progress: true


jobs:
  # Execute Dockerfile
    build:
        runs-on:
          group: arc-runners
        steps:
          - uses: actions/checkout@v4
          - name: Build the Docker image
            run: docker run -v $(pwd)/output:/output $(docker build -q .)
          - name: Upload artifact
            uses: actions/upload-artifact@v2
            with:
              name: output
              path: output
